local log = require("safe.log")

describe("safe.log", function()
    local captured

    before_each(function()
        captured = {}
        log.set_output(function(msg)
            captured[#captured + 1] = msg
        end)
        log.set_timestamp(function()
            return "2025-01-01T00:00:00"
        end)
        log.set_level(log.DEBUG)
        log.set_context(nil)
    end)

    describe("level constants", function()
        it("has correct ordering", function()
            assert.is_true(log.DEBUG < log.INFO)
            assert.is_true(log.INFO < log.WARN)
            assert.is_true(log.WARN < log.ERROR)
            assert.is_true(log.ERROR < log.NONE)
        end)
    end)

    describe("set_level / get_level", function()
        it("defaults to INFO", function()
            -- Reset by requiring fresh, but we set to DEBUG in before_each
            log.set_level(log.INFO)
            assert.are.equal(log.INFO, log.get_level())
        end)

        it("changes the level", function()
            log.set_level(log.ERROR)
            assert.are.equal(log.ERROR, log.get_level())
        end)
    end)

    describe("level gating", function()
        it("filters messages below current level", function()
            log.set_level(log.WARN)
            log.debug("ignored")
            log.info("ignored")
            log.warn("shown")
            log.error("also shown")
            assert.are.equal(2, #captured)
        end)

        it("shows all at DEBUG level", function()
            log.set_level(log.DEBUG)
            log.debug("d")
            log.info("i")
            log.warn("w")
            log.error("e")
            assert.are.equal(4, #captured)
        end)

        it("shows nothing at NONE level", function()
            log.set_level(log.NONE)
            log.debug("d")
            log.info("i")
            log.warn("w")
            log.error("e")
            assert.are.equal(0, #captured)
        end)
    end)

    describe("output format", function()
        it("includes timestamp and level", function()
            log.info("hello")
            assert.are.equal("[2025-01-01T00:00:00] [INFO] hello", captured[1])
        end)

        it("formats with arguments", function()
            log.info("count: %d", 42)
            assert.are.equal("[2025-01-01T00:00:00] [INFO] count: 42", captured[1])
        end)

        it("uses correct level names", function()
            log.debug("d")
            log.info("i")
            log.warn("w")
            log.error("e")
            assert.truthy(captured[1]:find("%[DEBUG%]"))
            assert.truthy(captured[2]:find("%[INFO%]"))
            assert.truthy(captured[3]:find("%[WARN%]"))
            assert.truthy(captured[4]:find("%[ERROR%]"))
        end)

        it("handles message with no format args", function()
            log.info("plain message")
            assert.are.equal("[2025-01-01T00:00:00] [INFO] plain message", captured[1])
        end)

        it("handles multiple format arguments", function()
            log.info("%s=%d (%.1f%%)", "score", 95, 95.5)
            assert.are.equal("[2025-01-01T00:00:00] [INFO] score=95 (95.5%)", captured[1])
        end)
    end)

    describe("context", function()
        it("includes context when set", function()
            log.set_context("mymodule")
            log.info("test")
            assert.are.equal("[2025-01-01T00:00:00] [INFO] [mymodule] test", captured[1])
        end)

        it("excludes context when nil", function()
            log.set_context(nil)
            log.info("test")
            assert.are.equal("[2025-01-01T00:00:00] [INFO] test", captured[1])
        end)

        it("get_context returns current context", function()
            log.set_context("ctx")
            assert.are.equal("ctx", log.get_context())
            log.set_context(nil)
            assert.is_nil(log.get_context())
        end)
    end)

    describe("set_output", function()
        it("directs output to custom handler", function()
            local custom = {}
            log.set_output(function(msg)
                custom[#custom + 1] = msg
            end)
            log.info("routed")
            assert.are.equal(1, #custom)
            assert.truthy(custom[1]:find("routed"))
        end)
    end)

    describe("set_timestamp", function()
        it("uses custom timestamp function", function()
            log.set_timestamp(function()
                return "CUSTOM_TS"
            end)
            log.info("test")
            assert.truthy(captured[1]:find("CUSTOM_TS"))
        end)
    end)

    describe("with_context", function()
        it("creates child logger with preset context", function()
            local child = log.with_context("child")
            child.info("from child")
            assert.are.equal("[2025-01-01T00:00:00] [INFO] [child] from child", captured[1])
        end)

        it("does not affect parent context", function()
            log.set_context("parent")
            local child = log.with_context("child")
            child.info("child msg")
            log.info("parent msg")
            assert.truthy(captured[1]:find("%[child%]"))
            assert.truthy(captured[2]:find("%[parent%]"))
        end)

        it("child respects level gating", function()
            log.set_level(log.ERROR)
            local child = log.with_context("child")
            child.debug("ignored")
            child.info("ignored")
            child.warn("ignored")
            child.error("shown")
            assert.are.equal(1, #captured)
        end)

        it("child supports all log levels", function()
            local child = log.with_context("ch")
            child.debug("d")
            child.info("i")
            child.warn("w")
            child.error("e")
            assert.are.equal(4, #captured)
            assert.truthy(captured[1]:find("%[DEBUG%]"))
            assert.truthy(captured[2]:find("%[INFO%]"))
            assert.truthy(captured[3]:find("%[WARN%]"))
            assert.truthy(captured[4]:find("%[ERROR%]"))
        end)

        it("child supports format arguments", function()
            local child = log.with_context("ch")
            child.info("val=%d", 42)
            assert.are.equal("[2025-01-01T00:00:00] [INFO] [ch] val=42", captured[1])
        end)
    end)
end)
